
services:
  mysqldb:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: full-stack-ecommerce
      MYSQL_ROOT_PASSWORD: reset@123
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    networks:
      - springapimysql-net

    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  api_service:
    image: harshaswamy789475/spring-boot-ecommerce

    build: ./backend/spring-boot-ecommerce
    restart: always
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=reset@123
    ports:
      - "8090:8080"
    depends_on:

      mysqldb:
        condition: service_healthy
    networks:
      - springapimysql-net

  angular_service:
    image: harshaswamy789475/angular-ecommerce
    build: ./frontend/angular-ecommerce
    restart: always
    ports:
      - "4200:80"
    depends_on:
      mysqldb:
        condition: service_healthy
      api_service:
        condition: service_started

    networks:
      - springapimysql-net

networks:
  springapimysql-net:
