version: "3.7"
services:
  mysqldb:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: full-stack-ecommerce
      MYSQL_ROOT_PASSWORD: reset@123
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    networks:
      - springapimysql-net

  api_service:
    build: ./backend/spring-boot-ecommerce
    restart: always
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=reset@123
    ports:
      - "8090:8080"
    depends_on:
      - mysqldb
    networks:
      - springapimysql-net

networks:
  springapimysql-net:
