AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Task Definition and Service Update with New Docker Image

Parameters:
  DockerImageURI:
    Type: String
    Description: The URI of the Docker image to be used in the task definition.
    MyCluster:
     Type: String
     Description: The URI of the Docker image to be used in the task definition.

Resources:

  MyTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: my-task-family
      ContainerDefinitions:
        - Name: my-container
          Image: !Ref DockerImageURI
          Memory: 512
          Cpu: 256
          Essential: true

  MyService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref MyCluster  # Your ECS cluster reference
      TaskDefinition: !Ref MyTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE_SPOT
      # Additional properties like LoadBalancer, etc.

Outputs:
  TaskDefinitionArn:
    Value: !Ref MyTaskDefinition
